Net:
  enc_type: 'resnet18'
  dec_type: 'unet_scse'
  num_filters: 8
  pretrained: False
Data:
  dataset: 'pascal'
#  target_size: (384, 768)
#  base_dir: /home/lijiahui/data/duanlie
  base_dir: /home/lijiahui/data/VOCdevkit/VOC2012
  num_classes: 21
Train:
  max_epoch: 50
  batch_size: 2
  fp16: False
  resume: False
  pretrained_path:
  output_dir: /home/lijiahui/models/seg_voc_saved_models
  log_dir: /home/lijiahui/models/seg_voc_saved_models
  eval_every_n_epochs: 3
  vis_flag: True
Loss:
#  loss_type: 'OhemCrossEntropy'
  loss_type: 'Focal'
  ignore_index: 255
  include_bg: True
#  alpha:
#    - 1
#    - 1
#    - 1
#    - 1
#    - 2
Optimizer:
  mode: 'adam'
  base_lr: 0.001
  t_max: 10
