Net:
  enc_type: 'resnet18'
  dec_type: 'unet_scse'
  num_filters: 8
  pretrained: False
Data:
  dataset: 'pascal'
  target_size: (384, 768)
  base_dir: D:/dataset/lumber/20191112/ceguang_2/voc
  num_classes: 5
Train:
  max_epoch: 50
  batch_size: 2
  fp16: False
  resume: False
  pretrained_path:
  output_dir: d:/working_directory/lumber/models/qiaopi
  log_dir: d:/working_directory/lumber/train_log/qiaopi
  eval_every_n_epochs: 1
  vis_flag: True
Loss:
  loss_type: 'Lovasz'
  ignore_index: 255
Optimizer:
  mode: 'adam'
  base_lr: 0.001
  t_max: 10
