Net:
  enc_type: 'resnet18'
  dec_type: 'unet_scse'
  num_filters: 8
  pretrained: True
Data:
  dataset: 'pascal'
  target_size: (384, 768)
  base_dir: D:/dataset/lumber/fanlongyan_seg_1/zhengguang_chongyan/voc
  num_classes: 5
Train:
  max_epoch: 50
  batch_size: 2
  fp16: False
  resume: False
  pretrained_path:
Loss:
  loss_type: 'Lovasz'
  ignore_index: 255
Optimizer:
  mode: 'adam'
  base_lr: 0.001
  t_max: 10
